site_app/urls.py
from django.urls import path
from site_app import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'site_app'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('sklep/', views.ShopView.as_view(), name='shop_view'),
    path('login/', views.LoginView.as_view(), name='login_view'),
    path('zarzadzaj/', views.ItemListView.as_view(), name='item_list'),
    path('zamowienia/', views.OrderListView.as_view(), name='order_list'),
    path('zmien_zdjecie/<int:item_id>', views.ChangePhotoView.as_view(), name='change_photo'),
    path('dodaj_produkt/', views.AddItemView.as_view(), name='add_item'),
    path('usun_produkt/<int:item_id>', views.DeleteItemView.as_view(), name='delete_item'),
    path('zamowienie/', views.OrderConfirmationView.as_view(), name='order_confirmation_view'),
    path('podsumowanie/', views.OrderSummaryView.as_view(), name='order_summary'),
    path('menu/', views.SellerMenu.as_view(), name='seller_menu'),
    path('wyloguj/', views.LogoutView.as_view(), name='logout'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sklep/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('site_app.urls')),
]

site_app/models.py
from decimal import Decimal

from django.contrib.auth.models import User
from django.db import models


class Item(models.Model):
    name = models.CharField(max_length=255)
    name_snakecase = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    unit = models.CharField(max_length=7)
    delivery_days = models.IntegerField()
    is_available = models.BooleanField()
    deleted = models.BooleanField(default=False)
    photo_url = models.CharField(max_length=256, default=None, null=True, blank=True)

    def __str__(self):
        return ('[DELETED] ' if self.deleted else '') + self.name


class Order(models.Model):
    id = models.IntegerField(primary_key=True, unique=True)
    id_str = models.CharField(max_length=7)
    sum = models.DecimalField(max_digits=6, decimal_places=2)
    payment_method = models.CharField(max_length=7, default='cash')
    items = models.CharField(max_length=8191)
    city = models.CharField(max_length=255)
    street = models.CharField(max_length=255)
    house_nr = models.CharField(max_length=7)
    flat_nr = models.CharField(max_length=7, null=True, blank=True, default=None)
    phone_number = models.CharField(max_length=15)
    email_address = models.EmailField()
    comments = models.CharField(max_length=511, default='')
    paid = models.BooleanField(default=False)
    completed = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)
    delivery_date = models.DateField()

    def __str__(self):
        return self.id_str

site_app/views.py
import json

from django import views
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import render, redirect
from django.utils import timezone

from decimal import Decimal
from site_app import models
from site_app import utils


class IndexView(views.View):
    """
    View for rendering the index page.
    """
    def get(self, request):
        """
        Renders the index page.

        :param request: HttpRequest object.

        :return: HttpResponse object rendering the index page.
        """
        return render(
            request,
            'site_app/index.html',
        )


class LoginView(views.View):
    """
    View for handling user login.
    """
    def get(self, request):
        """
        Renders the login page.

        :param request: HttpRequest object.

        :return: HttpResponse object rendering the login page.
        """
        return render(
            request,
            'site_app/login.html',
        )

    def post(self, request):
        """
        Handles user login form submission.

        1. Loads data from the POST form.
        2. Sets the user variable as None.
        3. Checks if a user with the given username exists in the database.
        4. If the user exists, checks if the password is correct; if not, reloads the login page.
        5. If the password is correct, logs the user in and redirects to the seller menu; if not, reloads the login page.

        :param request: HttpRequest object containing login form data.

        :return: HttpResponse object redirecting to the seller menu if login is successful, or reloads the login page.
        """
        data = request.POST
        user = None
        username = data['login']
        password = data['password']
        userdata = models.User.objects.filter(username=username).first()
        if userdata:
            user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            return redirect('site_app:seller_menu')


class ItemListView(LoginRequiredMixin, views.View):
    """
    View for displaying and managing a list of items.
    """
    def get(self, request):
        """
        Displays a list of items (products) for management.

        1. Loads non-deleted items (products) data from the database, orders them alphabetically by name, and converts the data to a list.
        2. Converts the price of each product to a string.
        3. Loads the item list into the page context data.
        4. Renders the item list page (products manager).

        :param request: HttpRequest object.

        :return: HttpResponse object rendering the item list page.
        """
        items = list(models.Item.objects.filter(deleted=False).order_by('name'))
        context = {
            'items': items
        }
        return render(
            request,
            'site_app/item_list.html',
            context
        )

    def post(self, request):
        """
        Handles the form submission for updating item data.

        1. Loads data from the POST form.
        2. Prepares a dictionary containing the loaded items data.
        3. Loads each item's data from the prepared dictionary.
        4. Loads the data of each item from the database and overwrites the item data with the new data from the dictionary, then saves each item's data.
        5. Redirects back to the item list page (products manager).

        :param request: HttpRequest object containing item update data.

        :return: HttpResponse object redirecting to the item list page.
        """
        data = request.POST
        new_data = utils.prepare_new_item_list_data(data)
        for item_name in new_data:
            item_data = new_data[item_name]
            item = models.Item.objects.get(name_snakecase=item_name)
            item.name = utils.format_and_capitalize_name(item_data['name'])
            item.name_snakecase = utils.convert_name_to_snakecase(item_data['name'])
            item.price = Decimal(item_data['price'].replace(',', '.'))
            item.unit = item_data['unit']
            item.is_available = True if 'availability' in item_data else False
            item.delivery_days = 0 if item_data['delivery_date'] == 'today' else 1
            item.save()
        return redirect('site_app:item_list')


class ShopView(views.View):
    """
    View for displaying the shop page and handling order submissions.
    """
    def get(self, request):
        """
        Displays the shop page with a list of available products.

        1. Loads non-deleted items (products) data from the database, orders them alphabetically by name, and converts the data to a list.
        2. Converts the price of each product to a string.
        3. Loads the item list into the page context data.
        4. Renders the shopping page (product list).

        :param request: HttpRequest object.

        :return: HttpResponse object rendering the shop page.
        """
        items = models.Item.objects.filter(deleted=False).order_by('name')
        order_data_json = request.COOKIES.get('order')
        if order_data_json:
            order_data = json.loads(order_data_json)
        for item in items:
            item.quantity = order_data[item.name_snakecase] if order_data_json else ''
        context = {
            'items': items,
        }
        errors = [str(x) for x in messages.get_messages(request)]
        if errors:
            context['errors'] = errors
        res = render(
            request,
            'site_app/shop.html',
            context
        )
        res.delete_cookie('order')
        return res

    def post(self, request):
        """
        Handles the form submission for placing an order.

        1. Loads data from the POST form.
        2. Prepares a dictionary containing the raw loaded order data.
        3. Loads the data of each ordered product from the database and prepares a full product list, counts the order sum, and calculates the order delivery date.
        4. Saves the order data, order sum, and delivery date to the session.
        5. Redirects to the order confirmation page.

        :param request: HttpRequest object containing order data.

        :return: HttpResponse object redirecting to the order confirmation page or shop page with errors.
        """
        data = request.POST
        order_raw, errors = utils.prepare_raw_order_data(request, data)
        if errors:
            res = redirect('site_app:shop_view')
            res.set_cookie('order', json.dumps(data))
            return res
        else:
            order_items, order_sum, order_delivery = utils.prepare_order_data(order_raw)
            request.session['order_items'] = json.dumps(order_items)
            request.session['order_sum'] = order_sum
            request.session['order_delivery'] = order_delivery
            return redirect('site_app:order_confirmation_view')


class OrderConfirmationView(views.View):
    """
    View for displaying and handling order confirmation.
    """
    def get(self, request):
        """
        Displays the order confirmation page.

        1. Loads user data if it exists in cookies.
        2. Loads the order sum from the session.
        3. Loads the order data, order sum (converted to string), delivery date, and user data (if it exists) into the page context.
        4. Renders the order confirmation page.

        :param request: HttpRequest object.

        :return: HttpResponse object rendering the order confirmation page.
        """
        user_data = request.COOKIES.get('user_data')
        order_sum = request.session['order_sum']
        context = {
            'order': json.loads(request.session['order_items']),
            'sum': order_sum,
            'delivery': request.session['order_delivery'],
            'user_data': json.loads(user_data) if user_data else None,
        }
        return render(
            request,
            'site_app/order_confirmation.html',
            context
        )

    def post(self, request):
        """
        Handles the form submission for confirming an order.

        1. Loads data from the POST form.
        2. Saves the new order in the database and gets a string representation of the new order ID.
        3. Converts the user data to JSON.
        4. Prepares a response object.
        5. Saves the user data to cookies if the user chose to save it, or deletes the user data if they didn't.
        6. Loads the user data, payment method, and order ID into the session.
        7. Redirects to the order summary page.

        :param request: HttpRequest object containing order confirmation data.

        :return: HttpResponse object redirecting to the order summary page.
        """
        data = request.POST
        id_str = utils.add_new_order(request, data)
        user_data = utils.convert_user_data_to_json(data)
        res = redirect('site_app:order_summary')
        if 'remember-data' in data:
            res.set_cookie('user_data', user_data, max_age=60*60*24*365*2)
        else:
            res.delete_cookie('user_data')
        request.session['user_data'] = user_data
        request.session['payment_method'] = data['payment_method']
        request.session['id'] = id_str
        return res


class OrderSummaryView(views.View):
    """
    View for displaying the order summary.
    """
    def get(self, request):
        """
        Displays the order summary page.

        1. Loads data from the session into the page context.
        2. Cleans the session.
        3. Renders the order summary view.

        :param request: HttpRequest object.

        :return: HttpResponse object rendering the order summary page.
        """
        context = {

site_app/templates/site_app/add_item.html
{% extends 'site_app/base.html' %}
{% block body %}
  <form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
    <div class="content-container data-container" id="user-data-container">
      <div style="width: 100%;">
        <h2>Dodaj produkt</h2>
      </div>
      <div style="width: 45%; text-align: right; margin-bottom: 10px;">
        Nazwa:
      </div>
      <div style="width: 45%; text-align: left; margin-bottom: 10px;">
        <input name="name" type="text" placeholder="wymagana" style="width: 200px; border: 1px solid gray; border-radius: 5px; margin-left: 5px; padding: 0px 5px 0px 5px; font-family: Arial, sans-serif;" required>
      </div>
      <div style="width: 45%; text-align: right; margin-bottom: 10px;">
        Cena:
      </div>
      <div style="width: 45%; text-align: left; margin-bottom: 10px;">
        <input name="price" type="text" placeholder="wymagana" style="width: 200px; border: 1px solid gray; border-radius: 5px; margin-left: 5px; padding: 0px 5px 0px 5px; font-family: Arial, sans-serif;" required>
      </div>
      <div style="width: 45%; text-align: right; margin-bottom: 10px;">
        Jednostka miary:
      </div>
      <div style="width: 45%; text-align: left; margin-bottom: 10px;">
        <select name="unit" style="width: 200px; border: 1px solid gray; border-radius: 5px; margin-left: 5px; padding: 0px 5px 0px 5px; font-family: Arial, sans-serif;">
          <option value="kg." selected>kg.</option>
          <option value="szt.">szt.</option>
        </select>
      </div>
      <div style="width: 45%; text-align: right; margin-bottom: 10px;">
        Aktualnie dostępny:
      </div>
      <div style="width: 45%; text-align: left; margin-bottom: 10px;">
        <input type="checkbox" name="is_available" checked>
      </div>
      <div style="width: 45%; text-align: right; margin-bottom: 10px;">
        Dostawa:
      </div>
      <div style="width: 45%; text-align: left; margin-bottom: 10px;">
        <div style="width: 100%;">
          <label>
            <input type="radio" name="delivery_date" value="today" checked>
            Dziś
          </label>
        </div>
        <div style="width: 100%;">
          <label>
            <input type="radio" name="delivery_date" value="tomorrow">
            Następny dzień roboczy
          </label>
        </div>
      </div>
      <div style="width: 45%; text-align: right; margin-bottom: 10px;">
        Zdjęcie:
      </div>
      <div style="width: 45%; text-align: left; margin-bottom: 10px;">
        <input type="file" name="add_photo" id="add_photo" style="width: 200px; border: 1px solid gray; border-radius: 5px; margin-left: 5px; font-family: Arial, sans-serif;" required>
      </div>
    </div>
    <div>
      <a href="{% url 'site_app:seller_menu' %}"><button type="button" class="button back_button">Wróć</button></a>
    </div>
    <div>
      <button type="submit" class="button submit_button">Zapisz</button>
    </div>
  </form>
{% endblock %}

site_app/templates/site_app/base.html
{% load static %}<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Warzywniak Banino Online</title>
  <link rel="stylesheet" href="{% static 'site_app/css/style.css' %}">{% block head %}
  {% endblock %}
</head>
<body>
  <img src="{% static 'site_app/images/logo.png' %}" id="logo">
{% block body %}
{% endblock %}
</body>
</html>

site_app/templates/site_app/change_photo.html
{% extends 'site_app/base.html' %}
{% block body %}
  <div>
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="content-container data-container" id="data-container">
        <div style="width: 100%;">
          <h2>Edycja zdjęcia produktu</h2>
        </div>
        <div style="width: 100%; margin-bottom: 10px;">
          {{ name }}
        </div>
        <div style="width: 100%">
          <img src="{{ photo_url }}" style="width: 300px; height: auto; margin-bottom: 10px;">
        </div>
        <div style="width: 100%">
          <input type="file" name="add_photo" id="add_photo" style="width: 200px; border: 1px solid gray; border-radius: 5px; margin-left: 5px; font-family: Arial, sans-serif;" required>
        </div>
      </div>
      <div>
        <a href="{% url 'site_app:item_list' %}"><button type="button" class="button back_button">Wróć</button></a>
      </div>
      <div>
        <button type="submit" class="button submit_button">Zapisz</button>
      </div>
    </form>
  </div>
{% endblock %}

site_app/templates/site_app/index.html
{% extends 'site_app/base.html' %}
{% block body %}
    <div class="content-container tiles-container" id="tiles-container">
      <div style="width: 100%;">
        <h2>Witamy w naszym warzywniaku online!</h2>
      </div>
      <div style="width: 100%;">
        Dziękujemy, że jesteś z nami! To dzięki takim klientom jak Ty możemy z dumą kontynuować naszą pasję i misję, która trwa już od 25 lat. Jesteśmy rodzinną firmą, która od pokoleń specjalizuje się w handlu owocami i warzywami, wybierając dla Ciebie produkty najwyższej jakości, pełne smaku i świeżości.
      </div>
      <div style="width: 100%;">
        Każdego dnia dokładamy wszelkich starań, by dostarczać owoce i warzywa, które nie tylko wzbogacają Twoje posiłki, ale także wspierają zdrowy styl życia. Współpracujemy z lokalnymi dostawcami, dbając o to, by każdy produkt trafiający na Twój stół był starannie wyselekcjonowany i pochodził z pewnych, ekologicznych źródeł.
      </div>
      <div style="width: 100%;">
        Z nami możesz mieć pewność, że wybierasz zdrowie, smak i tradycję. W naszym sklepie online znajdziesz bogaty wybór świeżych warzyw, soczystych owoców oraz produktów sezonowych – idealnych zarówno do codziennych posiłków, jak i wyjątkowych okazji.
      </div>
      <div style="width: 100%;">
        Dziękujemy, że obdarzasz nas swoim zaufaniem. Jesteśmy tu po to, by Twoje zakupy były proste, szybkie i przyjemne. Jeśli masz pytania lub potrzebujesz porady, zawsze chętnie Ci pomożemy – bo dla nas liczy się Twój komfort i zadowolenie.
      </div>
      <div style="width: 100%;">
        Zapraszamy do zakupów i dziękujemy, że jesteś częścią naszej historii!
      </div>
      <div>
        <a href="{% url 'site_app:shop_view' %}"><button type="button" class="button submit_button">Sklep</button></a>
      </div>
    </div>
{% endblock %}

site_app/templates/site_app/item_list.html
{% extends 'site_app/base.html' %}
{% block body %}
    <form method="POST" class="item-list-form">
    {% csrf_token %}
      <div class="content-container tiles-container" id="tiles-container">
        <div style="width: 100%;">
          <h2>Asortyment</h2>
        </div>
        <div style="width: 100%;">
          <input type="text" id="search-box" placeholder="Czego szukasz?" oninput="filterTiles()">
        </div>{% for item in items %}
        <div class="tile item-tile" id="{{ item.name_snakecase }}">
          <div style="margin: 5px 0px 5px 0px;">
            <input type="text" value="{{ item.name }}" style="display: inline-block; width: 75%;" name="{{item.name_snakecase}}-name">
          </div>
          <div>
            <a href="{% url 'site_app:change_photo' item.id %}" target="_blank">[Zmień zdjęcie]</a>
          </div>
          <div>
            <input type="text" value="{{ item.price|floatformat:"-2" }}" style="display: inline-block; width: 35px;" name="{{item.name_snakecase}}-price">
            zł /
            <select name="{{item.name_snakecase}}-unit">
              <option value="kg."{% if item.unit == 'kg.' %} selected{% endif %}>kg.</option>
              <option value="szt."{% if item.unit == 'szt.' %} selected{% endif %}>szt.</option>
            </select>
          </div>
          <div>
            <label>
              <input type="checkbox" name="{{item.name_snakecase}}-availability"{% if item.is_available %} checked{% endif %}>
            Dostępny
            </label>
          </div>
          <div>
            <label>
              <input type="radio" name="{{item.name_snakecase}}-delivery_date" value="today"{% if item.delivery_days == 0 %} checked{% endif %}>
              Dziś
            </label>
            <label>
              <input type="radio" name="{{item.name_snakecase}}-delivery_date" value="tomorrow"{% if item.delivery_days == 1 %} checked{% endif %}>
              Jutro
            </label>
          </div>
          <div>
            <a href="{% url 'site_app:delete_item' item.id %}">[Usuń produkt]</a>
          </div>
        </div>{% endfor %}
        <div style="display: inline;">
          <div>
            <a href="{% url 'site_app:seller_menu' %}"><button type="button" class="button back_button">Wróć</button></a>
          </div>
          <div>
            <button type="submit" class="button submit_button">Zapisz</button>
          </div>
        </div>
      </div>
    </form>
    <script>
        function filterTiles() {
            const searchQuery = document.getElementById('search-box').value.toLowerCase();
            const tiles = document.querySelectorAll('.tile');

            tiles.forEach(tile => {
                const tileId = tile.id.toLowerCase();
                if (searchQuery === "" || tileId.includes(searchQuery)) {
                    tile.classList.remove('hidden');
                } else {
                    tile.classList.add('hidden');
                }
            });
        }
    </script>
{% endblock %}

site_app/templates/site_app/login.html
{% extends 'site_app/base.html' %}
{% block body %}
  <div>
    <form method="POST">
      {% csrf_token %}
      <div class="content-container data-container" id="login-container">
        <div style="width: 100%;">
          <h2>Logowanie</h2>
        </div>
        <div class="label-container">
          <label class="login_field_label">Login:</label>
        </div>
        <div class="input-container">
          <input type="text" id="login" name="login" class="login_field">
        </div>
        <div class="label-container">
          <label class="login_field_label">Hasło:</label>
        </div>
        <div class="input-container">
          <input type="password" id="password" name="password" class="login_field">
        </div>
        <div>
          <button type="submit" class="button submit_button">Zaloguj</button>
        </div>
      </div>
    </form>
  </div>
{% endblock %}

site_app/templates/site_app/logout.html
{% extends 'site_app/base.html' %}
{% block body %}
    <div class="content-container tiles-container" id="tiles-container">
      <form method="POST">
      {% csrf_token %}
        <div style="width: 100%;">
          <h2>Komunikat</h2>
        </div>
        <div style="width: 100%;">
          Czy na pewno chcesz się wylogować?
        </div>
        <div>
          <a href="{% url 'site_app:seller_menu' %}"><button type="button" class="button back_button">Nie</button></a>
        </div>
        <div>
          <button type="submit" class="button submit_button">Tak</button>
        </div>
      </form>
    </div>
    <script>
        function filterTiles() {
            const searchQuery = document.getElementById('search-box').value.toLowerCase();
            const tiles = document.querySelectorAll('.tile');

            tiles.forEach(tile => {
                const tileId = tile.id.toLowerCase();
                if (searchQuery === "" || tileId.includes(searchQuery)) {
                    tile.classList.remove('hidden');
                } else {
                    tile.classList.add('hidden');
                }
            });
        }
    </script>
{% endblock %}

site_app/templates/site_app/order_list.html
{% extends 'site_app/base.html' %}
{% block body %}
    <div class="content-container tiles-container" id="user-data-container">
      <div style="width: 100%;">
        <h2>Zamówienia</h2>
      </div>
      <div style="width: 100%;">
        <input type="text" id="search-box" placeholder="Nr zam., nr tel. lub miejscowość" oninput="filterTiles()">
      </div>
      {% for order in orders %}
      <div class="tile{% if order.delivery_today %} today{% else %} tomorrow{% endif %}" id="{{ order.id_str }}_{{ order.id }}_{{ order.city }}_{{ order.phone_number }}">
       <div>
          {{ order.street }} {{ order.house_nr }}{% if order.flat_nr %}/{{ order.flat_nr }}{% endif %}
        </div>
        <div>
          {{ order.city }}{% if order.comments %} [!]{% endif %}
        </div>
        <div>
          <a href="tel:{{ order.phone_number }}">{{ order.phone_number }}</a>
        </div>
        <div>
          {{ order.sum|floatformat:"-2" }} zł {% if order.paid == True %}Zapł.{% elif order.payment_method == 'cash' %}got./kart.{% elif order.payment_method == 'blik' %}BLIK{% endif %}
        </div>
        <div>
          {{ order.items|length }} {% if order.completed and not order.paid %}Rezygnacja{% elif order.completed %}Dostarczono{% elif oder.paid %}Opłacone{% else %}Nieopłacone{% endif %}
        </div>
        <div>
          Dost: {{ order.delivery_date|date:"d.m.Y" }}
        </div>
        <div>
          Szczegóły
        </div>
      </div>
      {% endfor %}
      <div>
        <a href="{% url 'site_app:seller_menu' %}"><button type="button" class="button back_button">Wróć</button></a>
      </div>
    </div>
    <script>
        function filterTiles() {
            const searchQuery = document.getElementById('search-box').value.toLowerCase();
            const tiles = document.querySelectorAll('.tile');

            tiles.forEach(tile => {
                const tileId = tile.id.toLowerCase();
                if (searchQuery === "" || tileId.includes(searchQuery)) {
                    tile.classList.remove('hidden');
                } else {
                    tile.classList.add('hidden');
                }
            });
        }
    </script>
{% endblock %}

site_app/templates/site_app/remove_item.html
{% extends 'site_app/base.html' %}
{% block body %}
    <div class="content-container tiles-container" id="tiles-container">
      <form method="POST">
      {% csrf_token %}
        <div style="width: 100%;">
          <h2>Komunikat</h2>
        </div>
        <div style="width: 100%;">
          Czy na pewno chcesz usunąć {{ item.name }}? Jeśli produkt będzie w przyszłości dostępny, oznacz go tymczasowo jako niedostępny.
        </div>
        <div>
          <a href="{% url 'site_app:item_list' %}"><button type="button" class="button back_button">Nie</button></a>
        </div>
        <div>
          <button type="submit" class="button submit_button">Tak</button>
        </div>
      </form>
    </div>
    <script>
        function filterTiles() {
            const searchQuery = document.getElementById('search-box').value.toLowerCase();
            const tiles = document.querySelectorAll('.tile');

            tiles.forEach(tile => {
                const tileId = tile.id.toLowerCase();
                if (searchQuery === "" || tileId.includes(searchQuery)) {
                    tile.classList.remove('hidden');
                } else {
                    tile.classList.add('hidden');
                }
            });
        }
    </script>
{% endblock %}

site_app/templates/site_app/seller_menu.html
{% extends 'site_app/base.html' %}
{% block body %}
  <div>
    <form method="POST">
      {% csrf_token %}
      <div class="content-container data-container" id="login-container">
        <div style="width: 100%;">
          <h2>Menu</h2>
        </div>
        <div>
          <a href="{% url 'site_app:order_list' %}"><button type="button" class="button menu-button">Zamówienia</button></a>
        </div>
        <div>
          <a href="{% url 'site_app:item_list' %}"><button type="button" class="button menu-button">Produkty</button></a>
        </div>
        <div>
          <a href="{% url 'site_app:add_item' %}"><button type="button" class="button menu-button">Dodaj produkt</button></a>
        </div>
        <div>
          <a href="{% url 'site_app:logout' %}"><button type="button" class="button back_button">Wyloguj</button></a>
        </div>
      </div>
    </form>
  </div>
{% endblock %}

site_app/templates/site_app/shop.html
{% extends 'site_app/base.html' %}
{% block body %}
  <form method="POST">
  {% csrf_token %}
    <div class="content-container tiles-container" id="tiles-container">
      <div style="width: 100%;">
        <h2>Zobacz, co dla Ciebie mamy!</h2>
      </div>
      <div style="width: 100%;">
        <input type="text" id="search-box" placeholder="Czego szukasz?" oninput="filterTiles()">
      </div>
      <div style="width: 100%; display: flex; flex-wrap: wrap; justify-content: center;">
        <div style="width: 20px; height: auto; border: 3px solid #44aa11; border-radius: 5px;">
        </div>
        <div style="width: auto; margin-left: 5px;">
          - dostawa jeszcze dziś
        </div>
        <div style="width: 20px; height: auto; border: 3px solid red; border-radius: 5px; margin-left: 10px;">
        </div>
        <div style="width: auto; margin-left: 5px;">
          - dostawa w najbliższy dzień roboczy
        </div>
      </div>{% for item in items %}
      <div class="tile{% if item.delivery_days %} tomorrow{% else %} today{% endif %}" id="{{ item.name_snakecase }}">
        <div class="photo-container">
          <img src="{{ item.photo_url }}" class="photo-container" style="width: auto; height: auto;">
        </div>
        <div>
          {{ item.name }}
        </div>
        <div>
          {{ item.price|floatformat:"-2" }} zł / {{ item.unit }}
        </div>
        <div>
          Ilość:
          <input type="text" name="{{item.name_snakecase}}" style="display: inline-block; width: 35px;{% if item.name_snakecase in errors %} background-color: #ffcccb;{% endif %}" placeholder="{% if item.unit == 'szt.' %}0{% else %}0,00{% endif %}" value="{{ item.quantity }}">
          {{ item.unit }}
        </div>
      </div>
        {% endfor %}
    </div>
    <div>
      <a href="{% url 'site_app:index' %}"><button type="button" class="button back_button">Wróć</button></a>
    </div>
    <div>
      <button type="submit" class="button submit_button">Dalej</button>
    </div>
  </form>
  <script>
      function filterTiles() {
          const searchQuery = document.getElementById('search-box').value.toLowerCase();
          const tiles = document.querySelectorAll('.tile');

          tiles.forEach(tile => {
              const tileId = tile.id.toLowerCase();
              if (searchQuery === "" || tileId.includes(searchQuery)) {
                  tile.classList.remove('hidden');
              } else {
                  tile.classList.add('hidden');
              }
          });
      }
  </script>{% endblock %}